CREATE TABLE [dbo].[ContactUs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Email] NVARCHAR(256) NOT NULL, 
    [Subject] NVARCHAR(256) NOT NULL, 
    [Message] NVARCHAR(MAX) NOT NULL, 
    [Name] NVARCHAR(256) NOT NULL, 
    [IsResponded] BIT NOT NULL DEFAULT 0, 
    [MessageDate] DATETIME2 NOT NULL DEFAULT GETDATE()
)
